export const landOrAir = {
    land: [
        "wheeled",
        "assault walker",
        "walker",
        "submarine",
        "wheeled walker"
    ],
    air: [
        "repulsorcraft",
        "starfighter",
        "airspeeder",
        "space/planetary bomber",
        "sail barge",
        "repulsorcraft cargo skiff",
        "speeder",
        "landing craft",
        "gunship",
        "transport",
        "fire suppression ship",
        "droid starfighter",
        "air speeder",
        "droid tank",
        "corvette",
        "Star Destroyer",
        "Deep Space Mobile Battlestation",
        "Light freighter",
        "assault starfighter",
        "Starfighter",
        "Star dreadnought",
        "Medium transport",
        "Patrol craft",
        "Armed government transport",
        "Escort ship",
        "Star Cruiser",
        "Assault Starfighter",
        "Space cruiser",
        "Droid control ship",
        "yacht",
        "Space Transport",
        "Diplomatic barge",
        "freighter",
        "assault ship",
        "capital ship",
        "star destroyer",
        "cruiser"
    ]
}